"use strict";
exports.__esModule = true;
var persona_1 = require("./persona");
var futbolista_1 = require("./futbolista");
var entrenador_1 = require("./entrenador");
var masajista_1 = require("./masajista");
var seleccionFutbol_1 = require("./seleccionFutbol");
/* Persona */
var persona1 = new persona_1.Persona("Ricardo", "Gramuglia");
var persona2 = new persona_1.Persona("Eduardo", "Caballero");
console.log(persona1.getNombre());
console.log(persona2.getApellido());
persona1.setApellido("Guemes");
persona2.setNombre("Julieta");
console.log(persona1.getApellido());
console.log(persona2.getNombre());
/* Futbolista */
var futbolista1 = new futbolista_1.Futbolista("Diego", "Maradona", 10, "Boca Juniors");
var futbolista2 = new futbolista_1.Futbolista("Lionel", "Messi", 30, "Barcelona");
var listadoFutbolista = [futbolista1, futbolista2];
console.log(listadoFutbolista);
console.log(futbolista1.getNombre());
console.log(futbolista2.getApellido());
futbolista1.setApellido("Pelé");
futbolista2.setNombre("Román");
console.log(futbolista1.getApellido());
console.log(futbolista2.getNombre());
console.log(futbolista1.getDorsal());
futbolista2.setDorsal(99);
console.log(futbolista2.getDorsal());
console.log(futbolista1.getEquipo());
futbolista2.setEquipo("San Lorenzo");
console.log(futbolista2.getEquipo());
futbolista1.jugarPartido();
/* Entrenador */
var entrenador1 = new entrenador_1.Entrenador("Pep", "Guardiola", "Español");
var entrenador2 = new entrenador_1.Entrenador("Zinedine", "Zidane", "Francés");
var listadoEntrenador = [entrenador1, entrenador2];
console.log(listadoEntrenador);
console.log(entrenador1.getNombre());
console.log(entrenador2.getApellido());
entrenador1.setApellido("Bilardo");
entrenador2.setNombre("Raúl");
console.log(entrenador1.getApellido());
console.log(entrenador2.getNombre());
console.log(entrenador1.getNacionalidad());
entrenador2.setNacionalidad("Argentino");
console.log(entrenador2.getNacionalidad());
entrenador1.realizarEntrenamiento();
/* Masajista */
var masajista1 = new masajista_1.Masajista("María", "Alvarez", 3000);
var masajista2 = new masajista_1.Masajista("Nicolás", "Gómez", 2500);
var listadoMasajista = [masajista1, masajista2];
console.log(listadoMasajista);
console.log(masajista1.getNombre());
console.log(masajista2.getApellido());
masajista1.setApellido("Tito");
masajista2.setNombre("Patricio");
console.log(masajista1.getApellido());
console.log(masajista2.getNombre());
console.log(masajista1.getSueldo());
masajista2.setSueldo(10000);
console.log(masajista2.getSueldo());
masajista2.darMasaje();
/* Selección de Fútbol */
var seleccion1 = new seleccionFutbol_1.SeleccionFutbol("Argentina", listadoFutbolista, listadoEntrenador, listadoMasajista);
var seleccion2 = new seleccionFutbol_1.SeleccionFutbol("Brasil", listadoFutbolista, listadoEntrenador, listadoMasajista);
console.log(seleccion1.getPais());
seleccion2.setPais("España");
console.log(seleccion2.getPais());
seleccion1.convocarFutbolista(futbolista1);
console.log(seleccion1);
seleccion2.despedirFutbolista(futbolista2);
console.log(seleccion2);
seleccion1.contratarEntrenador(entrenador1);
console.log(seleccion1);
seleccion2.despedirEntrenador(entrenador2);
console.log(seleccion2);
seleccion1.contratarMasajista(masajista1);
console.log(seleccion1);
seleccion2.despedirMasajista(masajista2);
console.log(seleccion2);
