"use strict";
exports.__esModule = true;
var claseArchivo_1 = require("./claseArchivo");
var claseCarpeta_1 = require("./claseCarpeta");
var file1 = new claseArchivo_1.Archivo("File1");
var file2 = new claseArchivo_1.Archivo("File2");
var file3 = new claseArchivo_1.Archivo("File3");
console.log("Archivos: ", file1, file2, file3);
var folder1 = new claseCarpeta_1.Carpeta("Folder1", []);
console.log("Folder1: ", folder1);
folder1.agregar(file1);
console.log("Folder1: ", folder1);
var folder2 = new claseCarpeta_1.Carpeta("Folder2", []);
console.log("Folder2: ", folder2);
folder2.agregar(file2);
folder2.agregar(file3);
folder2.agregar(folder1);
console.log("Folder2: ", folder2);
folder2.buscar("Folder1");
